version: "3"
services:
  linkstart-mysql:
    image: mysql:8
    container_name: linkstart-mysql
    ports:
      - "3307:3306"
    networks:
      - linkstart-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}


  linkstart-api:
    build: .
    container_name: linkstart-api
    depends_on:
      - linkstart-mysql
    restart: on-failure
    ports:
      - "8081:8080"
    networks:
      - linkstart-network
    environment:
      - spring.datasource.url=jdbc:mysql://linkstart-mysql:3306/${MYSQLDB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}


networks:
  linkstart-network:
