version: "3"
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - springmysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}


  linkstartapi:
    depends_on:
      - mysqldb
    image: linkstartapi
    ports:
      - "8080:8080"
    networks:
      - springmysql
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/${MYSQLDB_DATABASE}?useSSL=false
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}


networks:
  springmysql:
