server:
  port: '8080'

spring:
  # Database config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL:localhost}:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  # JPA config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Use the .env file for the environment variable
  config:
    import: optional:file:.env[.properties]

  mvc:
    # Date format
    format:
      date: yyyy-MM-dd

jwt:
  secret: ${JWT_SECRET:611bd31f2abc10ac666eb377691d9bf61c6f397de8dc29c1d9c1d022d81f1a04}
  registerPassword: ${REGISTER_PASSWORD:localRegisterPassword}
