name: Deploy Docker Container

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build -t linkstart-api-image .
        docker tag linkstart-api-image garwalle/linkstart-api-image:latest
    - name: Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
        docker push garwalle/linkstart-api-image:latest
    - name: Deploy to Production
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: martin-jeanne.site
        username: martin
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull garwalle/linkstart-api-image
          docker stop linkstart-api
          docker rm linkstart-api
          docker run -d --name linkstart-api -p 8080:8080 \
          -e "SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.MYSQL_DATABASE }}:3306/${{ secrets.MYSQL_DATABASE }}?allowPublicKeyRetrieval=true&useSSL=false" \
          -e "SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USER }}" \
          -e "SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" \
          --net="linkstart" \
          garwalle/linkstart-api-image
